[theme]
base = "light"
primaryColor = "#FF571F"
backgroundColor = "#F8F8F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
